pipeline {
    agent any

    environment {
        VENV = 'venv'
    }

    stages {
        stage('Clone Specific Branch') {
            steps {
                git branch: 'main', credentialsId: 'github-token', url: 'https://github.com/flossiendabambi/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'python3 -m venv venv'
                sh './venv/bin/pip3 install --upgrade pip'
                sh './venv/bin/pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh './venv/bin/python3 -m pytest messaging_app/tests --junitxml=report.xml'
            }
        }

        stage('Publish Report') {
            steps {
                junit 'report.xml'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}
